package com.nicico.sales.enumeration;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum EContractDetailValueKey {
	NotImportant,
	QUANTITY,
	TOLERANCE,
	OPTION,
	SHIPMENT_START_DATE,
	SHIPMENT_END_DATE,
	LME_GRADE,
	MIN_BUNDLE_TONNAGE,
	MAX_BOUNDLE_TONNAGE,
	INCOTERM_VERSION,
	INCOTERM_RULES,
	SOURCE_PORT,
	PRICE_REFERENCE,
	AVERAGE_OF_WORKING_DAYS_OF_QUOTATIONAL_PERIOD,
	NUMBER_OF_DAYS_BEFORE_BL,
	NUMBER_OF_DAYS_AFTER_BL,
	PAYMENT_METHOD,
	PAYMENT_PERCENTAGE_OF_PROVISIONAL_INVOICE,
	INVOICE_CURRENCY,
	PAYMENT_CURRENCY,
	CURRENCY_RATE_DATE,
	SHARE_OF_INSPECTION_COST,
	T_UNIT
}
