package com.nicico.sales.enumeration;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum EContractDetailValueKey {
    NotImportant("NotImportant"),

    QUANTITY("QUANTITY"),
    TOLERANCE("TOLERANCE"),
    OPTION("OPTION"),
    SHIPMENT_START_DATE("SHIPMENT_START_DATE"),
    SHIPMENT_END_DATE("SHIPMENT_END_DATE"),
    LME_GRADE("LME_GRADE"),
    MIN_BUNDLE_TONNAGE("MIN_BUNDLE_TONNAGE"),
    MAX_BOUNDLE_TONNAGE("MAX_BOUNDLE_TONNAGE"),
    SOURCE_PORT("`SOURCE_PORT"),
    PRICE_REFERENCE("PRICE_REFERENCE"),
    AVERAGE_OF_WORKING_DAYS_OF_QUOTATIONAL_PERIOD("AVERAGE_OF_WORKING_DAYS_OF_QUOTATIONAL_PERIOD"),
    NUMBER_OF_DAYS_BEFORE_BL("NUMBER_OF_DAYS_BEFORE_BL"),
    NUMBER_OF_DAYS_AFTER_BL("NUMBER_OF_DAYS_AFTER_BL"),
    PAYMENT_METHOD("PAYMENT_METHOD"),
    PAYMENT_CURRENCY("PAYMENT_CURRENCY"),
    CURRENCY_RATE_DATE("CURRENCY_RATE_DATE"),
    SHARE_OF_INSPECTION_COST("SHARE_OF_INSPECTION_COST"),
    T_UNIT("T_UNIT"),
    TYPICAL_ASSAY("TYPICAL_ASSAY"),
    CONTRACT_SHIPMENT("CONTRACT_SHIPMENT"),
    WEIGHING_COST("WEIGHING_COST"),
    RATE_REFERENCE("RATE_REFERENCE"),
    INVOICE_CURRENCY("INVOICE_CURRENCY"),
    USD_AED_CONVERSION_RATE("USD_AED_CONVERSION_RATE"),
    PAYMENT_PERCENTAGE_OF_PROVISIONAL_INVOICE("PAYMENT_PERCENTAGE_OF_PROVISIONAL_INVOICE"),
    MOAS("MOAS"),
    SELLER_NAME("SELLER_NAME"),
    RECEIPT_OF_PROVISIONAL_INVOICE("RECEIPT_OF_PROVISIONAL_INVOICE"),
    START_SHIPMENT_DATE("START_SHIPMENT_DATE"),
    INCOTERM("INCOTERM"),
    LOAD_PORT("LOAD_PORT"),
    BUYER_NAME("BUYER_NAME"),
    BUYER_ADDRESS("BUYER_ADDRESS"),
    START_SHIPMENT_dATE("START_SHIPMENT_dATE"),
    BUYER_FAX("BUYER_FAX"),
    BUYER_PHONE("BUYER_PHONE"),
    SELLER_ADDRESS("SELLER_ADDRESS"),
    SELLER_FAX("SELLER_FAX"),
    SELLER_PHONE("SELLER_PHONE"),
    PRODUCED_IN("PRODUCED_IN"),
    INSPECTOR("INSPECTOR"),
    ANALYZED_TOLERANCE("ANALYZED_TOLERANCE"),
    ANALYZED_WEIGHT("ANALYZED_WEIGHT"),
    TYPICAL_TOLERANCE("TYPICAL_TOLERANCE"),
    TYPICAL_WEIGHT("TYPICAL_WEIGHT"),
    DRUM_WEIGHT("DRUM_WEIGHT"),
    DISCOUNT("DISCOUNT"),
    TC("TC"),
    RC("RC");

    private final String id;
}
