-- create index IDX_DBA_REMITTANCE_DET_INVID on TBL_WARH_REMITTANCE_DETAIL (f_inventory_id);
-- create index IDX_DBA_REMITTANCE_DESTOZINID on TBL_WARH_REMITTANCE_DETAIL (f_destination_tozine_id);
-- create index IDX_DBA_REMITTANCE_SRCTOZINID on TBL_WARH_REMITTANCE_DETAIL (f_source_tozine_id);
-- create index IDX_DBA_REMITTANCE_UNITID on TBL_WARH_REMITTANCE_DETAIL (f_unit_id);
-- create index IDX_DBA_WARHTOZIN_FADATE on TBL_WARH_TOZIN(DAT);
--
-- --
--
