 INSERT INTO TBL_WARH_ITEM_DETAIL (ID, C_CREATED_BY, D_CREATED_DATE, C_LAST_MODIFIED_BY,
            D_LAST_MODIFIED_DATE, N_VERSION, N_E_STATUS, B_EDITABLE, C_DESCRIPTION, F_ITEM_ID, C_NAME, C_NAME_EN) VALUES
            (97, 'saeb', TO_TIMESTAMP('2020-05-05 09:20:02.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, null, 0,
            default, default, null, 26030090, 'اکسید مولیبدن', null);
            INSERT INTO TBL_WARH_ITEM_DETAIL (ID, C_CREATED_BY, D_CREATED_DATE, C_LAST_MODIFIED_BY,
            D_LAST_MODIFIED_DATE, N_VERSION, N_E_STATUS, B_EDITABLE, C_DESCRIPTION, F_ITEM_ID, C_NAME, C_NAME_EN) VALUES
            (9, 'saeb', TO_TIMESTAMP('2020-05-05 09:20:02.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, null, 0, default,
            default, null, 28257000, 'مس کاتد ', null);
            INSERT INTO TBL_WARH_ITEM_DETAIL (ID, C_CREATED_BY, D_CREATED_DATE, C_LAST_MODIFIED_BY,
            D_LAST_MODIFIED_DATE, N_VERSION, N_E_STATUS, B_EDITABLE, C_DESCRIPTION, F_ITEM_ID, C_NAME, C_NAME_EN) VALUES
            (10, 'saeb', TO_TIMESTAMP('2020-05-05 09:20:02.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, null, 0,
            default, default, null, 28257000, 'مس کاتد لیچینگ سرچشمه', null);
            INSERT INTO TBL_WARH_ITEM_DETAIL (ID, C_CREATED_BY, D_CREATED_DATE, C_LAST_MODIFIED_BY,
            D_LAST_MODIFIED_DATE, N_VERSION, N_E_STATUS, B_EDITABLE, C_DESCRIPTION, F_ITEM_ID, C_NAME, C_NAME_EN) VALUES
            (11, 'saeb', TO_TIMESTAMP('2020-05-05 09:20:02.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, null, 0,
            default, default, null, 28257000, 'کاتد صادراتی', null);
            INSERT INTO TBL_WARH_ITEM_DETAIL (ID, C_CREATED_BY, D_CREATED_DATE, C_LAST_MODIFIED_BY,
            D_LAST_MODIFIED_DATE, N_VERSION, N_E_STATUS, B_EDITABLE, C_DESCRIPTION, F_ITEM_ID, C_NAME, C_NAME_EN) VALUES
            (114, 'saeb', TO_TIMESTAMP('2020-05-05 09:20:02.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, null, 0,
            default, default, null, 28257000, 'مس کاتد لیچینگ میدوک', null);
            INSERT INTO TBL_WARH_ITEM_DETAIL (ID, C_CREATED_BY, D_CREATED_DATE, C_LAST_MODIFIED_BY,
            D_LAST_MODIFIED_DATE, N_VERSION, N_E_STATUS, B_EDITABLE, C_DESCRIPTION, F_ITEM_ID, C_NAME, C_NAME_EN) VALUES
            (129, 'saeb', TO_TIMESTAMP('2020-05-05 09:20:02.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, null, 0,
            default, default, null, 28257000, 'کاتد داخلی', null);
            INSERT INTO TBL_WARH_ITEM_DETAIL (ID, C_CREATED_BY, D_CREATED_DATE, C_LAST_MODIFIED_BY,
            D_LAST_MODIFIED_DATE, N_VERSION, N_E_STATUS, B_EDITABLE, C_DESCRIPTION, F_ITEM_ID, C_NAME, C_NAME_EN) VALUES
            (86, 'saeb', TO_TIMESTAMP('2020-05-05 09:20:02.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, null, 0,
            default, default, null, 28257000, 'کاتد داخلی وارداتی ', null);
            INSERT INTO TBL_WARH_ITEM_DETAIL (ID, C_CREATED_BY, D_CREATED_DATE, C_LAST_MODIFIED_BY,
            D_LAST_MODIFIED_DATE, N_VERSION, N_E_STATUS, B_EDITABLE, C_DESCRIPTION, F_ITEM_ID, C_NAME, C_NAME_EN) VALUES
            (90, 'saeb', TO_TIMESTAMP('2020-05-05 09:20:02.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, null, 0,
            default, default, null, 28257000, 'کاتد پالایشگاهی', null);
            INSERT INTO TBL_WARH_ITEM_DETAIL (ID, C_CREATED_BY, D_CREATED_DATE, C_LAST_MODIFIED_BY,
            D_LAST_MODIFIED_DATE, N_VERSION, N_E_STATUS, B_EDITABLE, C_DESCRIPTION, F_ITEM_ID, C_NAME, C_NAME_EN) VALUES
            (95, 'saeb', TO_TIMESTAMP('2020-05-05 09:20:02.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, null, 0,
            default, default, null, 28257000, 'کاتد لیچینگ', null);
            INSERT INTO TBL_WARH_ITEM_DETAIL (ID, C_CREATED_BY, D_CREATED_DATE, C_LAST_MODIFIED_BY,
            D_LAST_MODIFIED_DATE, N_VERSION, N_E_STATUS, B_EDITABLE, C_DESCRIPTION, F_ITEM_ID, C_NAME, C_NAME_EN) VALUES
            (8, 'saeb', TO_TIMESTAMP('2020-05-05 09:20:02.000000', 'YYYY-MM-DD HH24:MI:SS.FF6'), null, null, 0, default,
            default, null, 74031100, 'کنسانتره مس ', null);
commit;
