spring:
  application:
    name: Sales
  profiles:
    active: Local
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: com.nicico.copper.common.hibernate.CustomOracleDialect
#        enable_lazy_load_no_trans: true
        format_sql: true
        hbm2ddl:
          schema_filter_provider: com.nicico.copper.common.hibernate.CustomSchemaFilterProvider
    open-in-view: false
  liquibase:
    database-change-log-table: Z_LIQ_CHANGELOG
    database-change-log-lock-table: Z_LIQ_CHANGELOG_LOCK
    change-log: classpath:db/changelog/liquibase-master.xml
    enabled: false
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  redis:
    port: 6379
  servlet:
    multipart:
      max-file-size: 1000MB

server:
  port: 8080
  servlet:
    context-path: /sales
    session:
      cookie:
        name: App_${spring.application.name}

management:
  endpoint:
    health:
      show-details: always

nicico:
  jpa:
    entity:
      package: com.nicico.sales.model
  google:
    mail:
      username: nicicofin@gmail.com
      password: salam@@123456
  mail:
    domain: nicico.com
    url: https://mail.nicico.com/ews/exchange.asmx
    username:
    password:
  upload:
    dir: /var/nicico/${spring.application.name}/
  workflow:
    update:
      mode: true
  bpmn:
    upload:
      dir: /var/nicico/${spring.application.name}/
  security:
    sys-password: password

---

spring:
  profiles: Production
  datasource:
    url: jdbc:oracle:thin:@//172.16.180.20:1521/pdb1.icico.net.ir
    username: sales
    password: sales
  redis:
    host: apps.icico.net.ir
    password: nicico
  security:
    oauth2:
      client:
        registration:
          oserver:
            client-id: ${spring.application.name}
            client-secret: password
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          oserver:
            authorization-uri: http://apps.icico.net.ir/oauth/authorize
            token-uri: http://apps.icico.net.ir/oauth/token
            user-info-uri: http://apps.icico.net.ir/user/info
            user-name-attribute: username

---

spring:
  profiles: Development
  datasource:
    url: jdbc:oracle:thin:@//oragnrt01.icico.net.ir:1521/pdb_dev01
    username: sales
    password: sales
  redis:
    host: devapp01.icico.net.ir
    password: nicico
  security:
    oauth2:
      client:
        registration:
          oserver:
            client-id: ${spring.application.name}
            client-secret: password
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          oserver:
            authorization-uri: http://devapp01.icico.net.ir/oauth/authorize
            token-uri: http://devapp01.icico.net.ir/oauth/token
            user-info-uri: http://devapp01.icico.net.ir/user/info
            user-name-attribute: username
nicico:
  apps:
    accounting: http://devapp01.icico.net.ir/accounting

---

spring:
  profiles: Local
  datasource:
    url: jdbc:oracle:thin:@//oragnrt01.icico.net.ir:1521/pdb_dev01
    username: saleslocal
    password: saleslocal
  redis:
    host: devapp01.icico.net.ir
    password: nicico
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          oserver:
            client-id: ${spring.application.name}
            client-secret: password
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          oserver:
            authorization-uri: http://devapp01.icico.net.ir/oauth/authorize
            token-uri: http://devapp01.icico.net.ir/oauth/token
            user-info-uri: http://devapp01.icico.net.ir/user/info
            user-name-attribute: username
nicico:
  upload:
    dir: c:/upload
  apps:
    accounting: http://devapp01.icico.net.ir/accounting
